discord:
  enabled: "${discord:false}"

twitch:
  enabled: "${twitch:true}"
  command-prefix: "!"

server:
  port: 9000

command:
  sprint:
    sign-up-duration: PT1M
    in-progress-duration: PT20M
    awaiting-counts-duration: PT3M

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gcp:
      firestore:
        emulator:
          enabled: true
        host-port: "localhost:9098"

command:
  sprint:
    sign-up-duration: PT30S
    in-progress-duration: PT30S
    awaiting-counts-duration: PT30S